{% set name = "segment-lidar" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/segment-lidar-{{ version }}.tar.gz
  sha256: a5a60c2823c7c24d510ceccce93f365cb2585e9e75caefb1c59c5cbebdaff293

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 3
  skip: true

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9

test:
  imports:
    - segment_lidar
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Yarroudh/segment-lidar
  summary: A package for segmenting LiDAR data using Segment-Anything Model (SAM) from Meta AI Research.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://yarroudh.gitbook.io/segment-lidar

extra:
  recipe-maintainers:
    - Yarroudh
    - akharroubi
